# Generated by Django 5.0 on 2023-12-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_comprada_gramos', models.IntegerField(blank=True, null=True)),
                ('costo_gramos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUnitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_comprada_unidades', models.IntegerField(blank=True, null=True)),
                ('costo_unidades', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_utilizada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelacionProductoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_comprada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_gramos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melipasteleria.materialgramos')),
                ('material_unitario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='melipasteleria.materialunitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='melipasteleria.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='relacion_materiales_gramos',
            field=models.ManyToManyField(related_name='materiales_gramos', through='melipasteleria.RelacionProductoMaterial', to='melipasteleria.materialgramos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='relacion_materiales_unitarios',
            field=models.ManyToManyField(related_name='materiales_unitarios', through='melipasteleria.RelacionProductoMaterial', to='melipasteleria.materialunitario'),
        ),
    ]
